backend:
  name: github
  repo: akinoccc/voran
  branch: main
  site_domain: akinoccc.netlify.app
  commit_messages:
    create: 'create({{collection}}): “{{slug}}”'
    update: 'update({{collection}}): “{{slug}}”'
    delete: 'delete({{collection}}): “{{slug}}”'
    uploadMedia: 'upload(media): “{{path}}”'
    deleteMedia: 'delete(media): “{{path}}”'
    openAuthoring: '''{{message}}'''
media_folder: content/images
public_folder: /images
collections:
  - name: site
    label: Site Configuration
    slug: '{{slug}}'
    files:
      - label: Site
        name: site
        file: config/site.json
        extension: json
        format: json
        fields:
          - {label: Logo, name: logo, widget: image}
          - {label: Favicon, name: favicon, widget: image}
          - label: Footer
            name: footer
            widget: object
            required: false
            fields:
              - {label: Copyright, name: copyright, widget: string}
              - label: links
                name: links
                widget: list
                fields:
                  - {label: Text, name: text, widget: string}
                  - {label: Url, name: url, widget: string}

      - label: Pages
        name: pages
        file: config/pages.json
        extension: json
        format: json
        fields:
          - label: Index,
            name: index
            widget: object
            required: false
            fields:
              - {label: Art, name: art, widget: string, description: 'plum, dots or random'}
              - {label: Description, name: description, widget: text, required: false}
          - label: Blog,
            name: blog
            widget: object
            required: false
            fields:
              - {label: Art, name: art, widget: string, description: 'plum, dots or random'}
              - {label: Description, name: description, widget: text, required: false}
          - label: Blog Detail,
            name: blog_detail
            widget: object
            required: false
            fields:
              - {label: Art, name: art, widget: string, description: 'plum, dots or random'}
              - {label: Description, name: description, widget: text, required: false}
          - label: Projects,
            name: projects
            widget: object
            required: false
            fields:
              - {label: Art, name: art, widget: string, description: 'plum, dots or random'}
              - {label: Description, name: description, widget: text, required: false}

      - label: Social Link
        name: social
        file: config/social.json
        extension: json
        format: json
        widget: object
        fields:
          - {label: Github, name: github, widget: string, required: false}
          - {label: Discord, name: discord, widget: string, required: false}
          - {label: X, name: x, widget: string, required: false}
          - {label: Email, name: email, widget: string, required: false}
          - {label: RSS, name: rss, widget: string, required: false}

  - name: home
    label: Home
    slug: '{{slug}}'
    files:
      - label: Home
        name: home
        file: content/home
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
  - name: articles
    label: Articles
    folder: content/articles
    create: true
    slug: '{{slug}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: text, required: false}
      - {label: Hero Image, name: hero_image, widget: image, required: false}
      - {label: Draft, name: draft, widget: boolean, required: false}
      - {label: Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}

  - name: projetcs
    label: Projects
    folder: content/projects
    create: true
    extension: yaml
    format: yaml
    slug: '{{slug}}'
    fields:
      - {label: Category, name: category, widget: string}
      - label: Projects
        name: projects
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Link, name: link, widget: string, required: false}
          - {label: Icon, name: icon, widget: image, required: false}
          - {label: Description, name: description, widget: text, required: false}
