backend:
  name: github
  repo: akinocccc/voran
  branch: main
  site_domain: akinoccc.netlify.app
media_folder: content/images
public_folder: /images
collections:
  - name: articles
    label: Articles
    folder: content/articles
    create: true
    slug: '{{slug}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: text, required: false}
      - {label: Hero Image, name: hero_image, widget: image, required: false}
      - {label: Draft, name: draft, widget: boolean, required: false}
      - {label: Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}

  - name: projetcs
    label: Projects
    folder: content/projects
    create: true
    extension: yaml
    format: yaml
    slug: '{{slug}}'
    fields:
      - {label: Category, name: category, widget: string}
      - label: Projects
        name: projects
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Link, name: link, widget: string}
          - {label: Icon, name: icon, widget: image}
          - {label: Description, name: description, widget: text}
